version: '3.4'

services:
  db:
    image : "mcr.microsoft.com/azure-sql-edge"
    ports :
      - "1433:1433"
    restart: always
    environment:
       MSSQL_PID : "Developer"
       MSSQL_USER : "SA"
       MSSQL_SA_PASSWORD : "MyPass@word"
       ACCEPT_EULA: "Y"
  synelproject:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - MSSQL_CONNECTION_STRING=Server=db,1433;Database=SAPExDb;User Id=SA;Password=MyPass@word
    ports:
      - "9090:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - db